filepath:
  blacklist: "classpath:/customer_blacklist.csv"
  voucher: "classpath:/sample.csv"

mysql:
  user-id: "root"
  password: "1234"

name:
  voucher:
    fixed-amount-voucher: "FixedAmountVoucher"
    percent-discount-voucher: "PercentDiscountVoucher"

